<!-- Scriptz -->
{{
    HTML::script('/bower_components/jquery/dist/jquery.min.js'),
    HTML::script('/bower_components/velocity/velocity.js'),
    HTML::script('/bower_components/moment/min/moment-with-locales.min.js'),
    HTML::script('/bower_components/angular/angular.js'),
    HTML::script('/bower_components/lumx/dist/lumx.js'),
    HTML::script('/bower_components/angular-resource/angular-resource.js'),
    HTML::script('/bower_components/angular-ui-router/release/angular-ui-router.min.js'),
    HTML::script('/js/JFDApp.js'),
    HTML::script('/js/Controllers/RegisterController.js'),
    HTML::script('/js/Controllers/LoginController.js'),
    HTML::script('/js/Controllers/HomeController.js'),
    HTML::script('/js/Controllers/ProjectsController.js'),
    HTML::script('/js/Services/Resources.js'),
    HTML::script('/js/Directives/student.js'),
    HTML::script('/js/Directives/week.js'),
    HTML::script('/js/Directives/project.js')
}}
